# Generated by Django 3.0.3 on 2020-05-16 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='feed',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
